application: color-name-app
version: 1
runtime: python27
api_version: 1
threadsafe: true

libraries:
- name: PIL
  version: "1.1.7"

handlers:
- url: /css
  static_dir: web/css

- url: /images
  static_dir: web/images

- url: /js
  static_dir: web/js

- url: /api/v1/login
  secure: always
  script: api.app
  
- url: /api/v1/save_test
  login: required
  secure: always
  script: api.app

- url: /api/.*
  script: api.app
  
- url: /task/.*
  secure: always
  login: admin
  script: task.app

- url: /
  script: main.app
  
- url: /.*
  script: user.app